### ISSUE TITLE
Fix badges

### ISSUE THREAD

**Issue by Trolldemorted** [enowars/EnoEngine#122]
- gh actions ci
- gh container registry
- nuget?

**Comment by DanielHabenicht** [comment]
What CI are you using now? 
I can see badges for Azure DevOps but also Github Actions.

**Comment by ldruschk** [comment]
We migrated from Azure DevOps to GitHub actions, but still have the Azure DevOps badge. So it should be the following link, feel free to add that to your already open PR

https://github.com/enowars/EnoEngine/actions/workflows/ci.yml/badge.svg
