### ISSUE TITLE
Improve statistics logging

### ISSUE THREAD

**Issue by Trolldemorted** [enowars/EnoEngine#27]
We want to have data in fancy graphs! E.g.
- a pie chart with submissions/$timeunit per team (with subcharts displaying ok/invalid/dup)
- a graph displaying total submissions over time
- a graph displaying queue contention
- system load
- ...

So far we have used Elk to display simple graphs. @5aint2ero could you advise what we should use? Can @enowars/engineering output well-formatted json and you do grafana magic and we get fancy graphs?

**Comment by 5aint2ero** [comment]
I propose we do something like this : [https://docs.influxdata.com/telegraf/v1.14/data_formats/input/json/](https://docs.influxdata.com/telegraf/v1.14/data_formats/input/json/)

**Comment by Trolldemorted** [comment]
Telegraf is the thingy that takes input and transports it to grafana, correct? Should it be done before saturday/do we have a grafana endpoint on saturday?

**Comment by 5aint2ero** [comment]
Correct. We will have a grafana endpoint on Saturday and if you have time to implement it it would be nice, but it's not a priority I think.

**Comment by Trolldemorted** [comment]
cc @mauricesvp

**Comment by 5aint2ero** [comment]
cc @ciklista

**Comment by mauricesvp** [comment]
`a pie chart with submissions/$timeunit per team (with subcharts displaying ok/invalid/dup)`
The `per team` part is still an open issue, see #77 

The rest shouldTM be working now in kibana and grafana.
