### ISSUE TITLE
Document the flag submission endpoint responses

### ISSUE THREAD

**Issue by ldruschk** [enowars/EnoEngine#43]
and make sure they end up on the landing page once it's done so that teams can adjust their tools if they want to

**Comment by mauricesvp** [comment]
Just a heads up @Savallator @feist-code
You might want to include information like this on the landing page. I'm not quite sure though whether this fits best into "Rules", "FAQ" or somewhere else.

**Comment by mauricesvp** [comment]
For reference: https://github.com/enowars/EnoEngine#post- under `Response`
