### ISSUE TITLE
Include round start time and round length in scoreboard API

### ISSUE THREAD

**Issue by ldruschk** [enowars/EnoEngine#65]
https://github.com/enowars/EnoEngine#scoreboard-api

This allows displaying live progress bars in the Scoreboard

**Comment by ldruschk** [comment]
Upon closer inspection the scoreboard doesn't adhere to the specification at all. The way it is currently implemented seems fine, but it is missing the FirstBlood information.

Also the numerical `ServiceStatus` isn't documented anywhere.

**Comment by mauricesvp** [comment]
Do you mean the old scoreboard? That is to be expected since we changed the specs just now while not changing the old scoreboard at all.

Also ServiceStatus is an [enum](https://github.com/enowars/EnoEngine/blob/89360db7f174ae5d3994502993270f4e41879713/EnoCore/Models/Database/RoundTeamServiceState.cs#L7)

**Comment by ldruschk** [comment]
@Trolldemorted told me I had to look at the /services/data/scoreboard<roundnum>.json files, are those not the correct ones?

**Comment by Trolldemorted** [comment]
Those are the correct ones, they just don't match the spec

**Comment by ldruschk** [comment]
> Also ServiceStatus is an [enum](https://github.com/enowars/EnoEngine/blob/89360db7f174ae5d3994502993270f4e41879713/EnoCore/Models/Database/RoundTeamServiceState.cs#L7)

Even then it would still be nice to have it documented where the Scoreboard API is

**Comment by ldruschk** [comment]
Or simply pass it along as a string so changes in the order of the enum declaration don't cause issues
