### ISSUE TITLE
Include the first bloods in the scoreboard.json

### ISSUE THREAD

**Issue by ldruschk** [enowars/EnoEngine#68]
I am not sure if this is a feature request or a bug report, but if this is already implemented it isn't working. Otherwise please implement it :D

Somewhat related: It would be a good idea to indicate whether the StoreIndex starts at 0 or 1 in the specification.

**Comment by domenukk** [comment]
I'm pro 0 based indexes, especially if checkers need to fix engine bugs with modulo 😄

**Comment by Trolldemorted** [comment]
Which engine bug are you referring to?

**Comment by ldruschk** [comment]
Apparently it is using 1 based indexes and it assumes that in the scoreboard as well, but on the scoreboard-side changing this would simply require a `+1` in a single line. I guess since everything else in the scoreboard (ServiceId and TeamId) is 1 based that would make sense, but I honestly don't care as long as it is documented

**Comment by Trolldemorted** [comment]
```
[{
	"TeamId": 2,
	"Timestamp": "2020-06-21T08:06:52.675Z",
	"TimeEpoch": 1592726812.675132,
	"RoundId": 1869,
	"StoreDescription": "StoreDescription",
	"StoreIndex": 0
}, {
	"TeamId": 1,
	"Timestamp": "2020-06-21T08:06:52.675Z",
	"TimeEpoch": 1592726812.6757717,
	"RoundId": 1869,
	"StoreDescription": "StoreDescription",
	"StoreIndex": 1
}]
```
this looks very 0 based to me, and iirc it should be 0 based

**Comment by ldruschk** [comment]
Yeah, accidentally used the second flag store of aa service with two flag stores for testing and it was displayed in the first flagstore, which I assumed meant that it was the first flagstore and displayed correctly.

So this appears to be working now, but I am leaving this issue open until this is documented in the API specification

**Comment by mauricesvp** [comment]
The doc seems to be up to date, or what's still missing? @ldruschk

**Comment by Savallator** [comment]
The docs are surely not up to date... the scoreboardinfo json is not even documented our

**Comment by Trolldemorted** [comment]
The firstblood also suffers from this issue: https://github.com/enowars/EnoEngine/issues/26#issuecomment-647055640

**Comment by Trolldemorted** [comment]
#26 is closed, but the timestamps aren't used yet

**Comment by Savallator** [comment]
They are...
