### ISSUE TITLE
Acquire / Log data about invalid submissions to the Flagsubmission

### ISSUE THREAD

**Issue by MMunier** [enowars/EnoEngine#77]
While this is not a feature needed by the engine for the CTF,
it is in the interest by our CTF-Team to be able to get Statistics and deduce the Behavior of other teams.

**Comment by Savallator** [comment]
Its not that easy, because that part is quite heavily optimized for performance, but i suppose we could insert a log message when performance testing to see how it goes. Keep in mind that the logging is already really crowded right now...

**Comment by Trolldemorted** [comment]
done for enowars4
